#- name: Backup file config snmpd.conf old
#  template:
#    src=snmpd.conf
#    dest=/etc/snmp/snmpd.conf

- name: Copy new config file snmpd.conf
  template:
    src=snmpd.conf
    dest=/etc/snmp/snmpd.conf

- name: Start service snmpd
  service: name=snmpd state=restarted enabled=true

